"""Dataset access for the anomaly-detection platform.

Preferred source: the ULB "Credit Card Fraud Detection" dataset (Dal Pozzolo
et al., 2015) -- the most widely used public benchmark for tabular anomaly
detection. It is ~150 MB and sits behind a Kaggle login, so it cannot be
fetched by a plain ``git clone && pip install``.

Resolution order:

1. ``data/creditcard.csv`` -- if you have downloaded the real Kaggle file,
   drop it here and everything downstream uses it automatically.
2. ``data/transactions.csv`` -- a seeded synthetic stand-in generated by this
   module with the same schema (Time, V1..V28, Amount, Class) and the same
   shape of problem: PCA-style uncorrelated components, extreme class
   imbalance, and a minority class that is only partially separable.

Which source was used is recorded in every artifact, so no metric in this
project can be mistaken for a real-benchmark result.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

DATA_DIR = Path(__file__).resolve().parent
REAL_CSV = DATA_DIR / "creditcard.csv"
SYNTHETIC_CSV = DATA_DIR / "transactions.csv"

SEED = 20260913
N_ROWS = 60_000
N_COMPONENTS = 28
FRAUD_RATE = 0.005  # 0.5%; see module note in README on why not 0.00173

# Components the synthetic fraud signal lives in. Chosen to mirror the fact
# that in the real dataset only a handful of components carry most of the
# separation -- the detector still has to find them among 28.
SIGNAL_COMPONENTS = [9, 11, 13, 16, 3]  # 0-indexed -> V10, V12, V14, V17, V4


def generate(n_rows: int = N_ROWS, seed: int = SEED) -> pd.DataFrame:
    """Generate the seeded synthetic transaction table."""
    rng = np.random.default_rng(seed)
    n_fraud = int(round(n_rows * FRAUD_RATE))
    n_normal = n_rows - n_fraud

    # PCA components: uncorrelated, zero-mean, geometrically decaying variance,
    # which is what a PCA transform of a real transaction table looks like.
    scales = 1.9 * np.exp(-np.arange(N_COMPONENTS) / 16.0) + 0.25

    normal = rng.standard_normal((n_normal, N_COMPONENTS)) * scales
    # A little kurtosis so "unusual but legitimate" rows exist and the task is
    # not a clean two-Gaussian separation.
    heavy = rng.random(n_normal) < 0.012
    normal[heavy] *= rng.uniform(1.7, 2.5, size=(heavy.sum(), 1))

    fraud = rng.standard_normal((n_fraud, N_COMPONENTS)) * scales
    # Heterogeneous difficulty: some frauds are blatant, many are marginal.
    strength = rng.gamma(shape=2.0, scale=0.85, size=(n_fraud, 1)).clip(0.15, 4.0)
    direction = rng.choice([-1.0, 1.0], size=(n_fraud, len(SIGNAL_COMPONENTS)))
    for j, comp in enumerate(SIGNAL_COMPONENTS):
        fraud[:, comp] += direction[:, j] * strength[:, 0] * 1.75 * scales[comp]
    fraud *= rng.uniform(1.0, 1.3, size=(n_fraud, 1))  # wider spread overall

    components = np.vstack([normal, fraud])
    labels = np.concatenate([np.zeros(n_normal, int), np.ones(n_fraud, int)])

    # Amount: heavy-tailed, frauds skew toward small card-testing amounts plus
    # an occasional large hit.
    amount = np.where(
        labels == 1,
        rng.lognormal(mean=2.4, sigma=1.7, size=n_rows),
        rng.lognormal(mean=3.3, sigma=1.1, size=n_rows),
    ).round(2).clip(0.0, 25_000.0)

    # Time: seconds over a 48-hour window, normals following a diurnal cycle,
    # frauds mildly over-represented overnight.
    hour_normal = rng.choice(24, size=n_rows, p=_diurnal_pmf())
    hour_fraud = rng.choice(24, size=n_rows, p=_nocturnal_pmf())
    hour = np.where(labels == 1, hour_fraud, hour_normal)
    day = rng.integers(0, 2, size=n_rows)
    time_s = day * 86_400 + hour * 3600 + rng.integers(0, 3600, size=n_rows)

    frame = pd.DataFrame(components, columns=[f"V{i + 1}" for i in range(N_COMPONENTS)])
    frame.insert(0, "Time", time_s)
    frame["Amount"] = amount
    frame["Class"] = labels

    # Realistic defects for the Data Preparation phase to handle.
    frame = frame.sample(frac=1.0, random_state=seed).reset_index(drop=True)
    dup_idx = rng.choice(frame.index, size=90, replace=False)
    frame = pd.concat([frame, frame.loc[dup_idx]], ignore_index=True)
    null_idx = rng.choice(frame.index, size=120, replace=False)
    frame.loc[null_idx, "Amount"] = np.nan
    neg_idx = rng.choice(frame.index.difference(null_idx), size=40, replace=False)
    frame.loc[neg_idx, "Amount"] = -frame.loc[neg_idx, "Amount"].abs()
    return frame.sample(frac=1.0, random_state=seed + 1).reset_index(drop=True)


def _diurnal_pmf() -> np.ndarray:
    hours = np.arange(24)
    w = 1.0 + np.cos((hours - 14) / 24 * 2 * np.pi)
    w = w + 0.15
    return w / w.sum()


def _nocturnal_pmf() -> np.ndarray:
    hours = np.arange(24)
    w = 1.0 + 0.9 * np.cos((hours - 2) / 24 * 2 * np.pi)
    w = w + 0.2
    return w / w.sum()


def load() -> tuple[pd.DataFrame, str]:
    """Return ``(frame, source_label)``, generating the fallback if needed."""
    if REAL_CSV.exists():
        return pd.read_csv(REAL_CSV), "kaggle-creditcard"
    if not SYNTHETIC_CSV.exists():
        generate().to_csv(SYNTHETIC_CSV, index=False)
    return pd.read_csv(SYNTHETIC_CSV), "synthetic-fallback"


if __name__ == "__main__":
    frame = generate()
    SYNTHETIC_CSV.parent.mkdir(parents=True, exist_ok=True)
    frame.to_csv(SYNTHETIC_CSV, index=False)
    print(f"wrote {SYNTHETIC_CSV} rows={len(frame):,} frauds={int(frame['Class'].sum())} "
          f"prevalence={frame['Class'].mean():.4%}")
